version: '3.8'

services:
  # Servicio para la aplicación Flask principal
  main_app:
    build:
      context: ./main_app # ¡IMPORTANTE! El contexto es el directorio main_app
      dockerfile: Dockerfile_app
    ports:
      - "5000:5000"
    volumes:
      - ./main_app:/app
      - ./knowledge:/app/knowledge
      - ./core_logic:/app/core_logic
    environment:
      - FLASK_ENV=development
      - MQTT_BROKER_ADDRESS=host.docker.internal
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=your_mqtt_user
      - MQTT_PASSWORD=your_mqtt_password
    depends_on:
      - ml_server

  # Servicio para el servidor de modelo de Machine Learning (solo embeddings)
  ml_server:
    build:
      context: ./ml_server # ¡IMPORTANTE! El contexto es el directorio ml_server
      dockerfile: Dockerfile_ml
    ports:
      - "5001:5001"
    volumes:
      - ./ml_server:/app_code # Monta el código de la aplicación en /app_code
    environment:
      - FLASK_ENV=development
    dns:
      - 8.8.8.8

volumes:
  pytorch_models_data:
