version: '3.8'

services:
  main_app:
    build:
      context: .
      dockerfile: ./main_app/Dockerfile_app
    # Con network_mode: host, los puertos ya no se mapean así.
    # El contenedor usa directamente los puertos del host.
    # ports:
    #   - "5000:5000"
    volumes:
      - ./main_app:/app/main_app
      - ./knowledge:/app/knowledge
      - ./core_logic:/app/core_logic
    environment:
      - FLASK_ENV=development
      - MQTT_BROKER_ADDRESS=192.168.1.11
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=leo
      - MQTT_PASSWORD=Kolke.2576
      - GEMINI_API_KEY=AIzaSyA_iF4rVbLVprHCbsiSGshFxFu8CXSsGvU
      # Cuando usas network_mode: host, los servicios se comunican a través de localhost
      - ML_SERVER_INTERNAL_IP=127.0.0.1 # ¡CAMBIO CLAVE! Ahora es localhost
    network_mode: host # ¡CAMBIO CLAVE!
    depends_on:
      - ml_server

  ml_server:
    build:
      context: ./ml_server
      dockerfile: Dockerfile_ml
    # Con network_mode: host, los puertos ya no se mapean así.
    # El contenedor usa directamente los puertos del host.
    # ports:
    #   - "5001:5001"
    volumes:
      - ./ml_server:/app_code
    environment:
      - FLASK_ENV=development
    network_mode: host # ¡CAMBIO CLAVE!
    dns:
      - 8.8.8.8

# Eliminamos la sección networks si usamos network_mode: host
# networks:
#   smart_home_network:
#     ipam:
#       config:
#         - subnet: 172.20.0.0/24
