# Usa una imagen base oficial de Python basada en Debian Bullseye
FROM python:3.9-slim-bullseye

# Establece el directorio de trabajo en /app dentro del contenedor
WORKDIR /app

# Instala el paquete python-is-python3 y actualiza pip
RUN apt-get update && \
    apt-get install -y --no-install-recommends python-is-python3 && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip

# Copia los archivos de requisitos e instálalos
COPY requirements_app.txt .
RUN pip install --no-cache-dir -r requirements_app.txt

# Copia todos los archivos de tu aplicación al contenedor
# Esto incluye app.py, y los directorios core_logic, knowledge, static, templates
COPY . .

# Expone el puerto en el que se ejecutará la aplicación Flask
EXPOSE 5000

# Define el comando para ejecutar la aplicación
CMD ["python", "app.py"]
