# Dockerfile_ml (ubicado en ~/Smart-Home-AI/ml_server/Dockerfile_ml)

FROM python:3.9-slim-bullseye

WORKDIR /app

# Instalar dependencias del sistema si es necesario
RUN apt-get update && \
    apt-get install -y --no-install-recommends python-is-python3 && \
    rm -rf /var/lib/apt/lists/*

# Copiar el archivo de requisitos del servidor ML y luego instalar las dependencias de Python.
COPY ml_server/requirements_ml.txt .
RUN pip install --no-cache-dir -r requirements_ml.txt

# Copiar el código de la aplicación del servidor ML
COPY ml_server/ml_server.py ./ml_server/

# Copiar la lógica central (código compartido)
COPY core_logic/ ./core_logic/

# Establecer el punto de entrada para el servidor ML con la ruta completa a python
CMD ["/usr/local/bin/python", "ml_server/ml_server.py"]
