# Usa una imagen base con Python y herramientas de desarrollo basada en Debian Bullseye
FROM python:3.9-slim-bullseye

# Establece el directorio de trabajo dentro del contenedor.
WORKDIR /app_code

# Instala las dependencias básicas necesarias.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python-is-python3 && rm -rf /var/lib/apt/lists/*

# Copia los archivos de requisitos e instálalos.
COPY requirements_ml.txt .
RUN pip install --no-cache-dir -r requirements_ml.txt

# Copia el código de la aplicación (ml_server.py)
COPY ml_server.py .

# Expone el puerto que usará la aplicación Flask
EXPOSE 5001

# Comando para ejecutar la aplicación Flask
CMD ["python", "ml_server.py"]
